apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: group-sync-patches
spec:
  serviceAccountRef:
    name: default
  patches:
    keycloak-credentials:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        namespace: group-sync-operator
        name: keycloak-credentials
      sourceObjectRefs:
        - apiVersion: v1
          kind: Secret
          namespace: keycloak
          name: keycloak-initial-admin
      patchTemplate: |
        data:
          username: {{ (index . 1).data.username }}
          password: {{ (index . 1).data.password }}
      patchType: application/merge-patch+json
    group-sync:
      targetObjectRef:
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: GroupSync
        namespace: group-sync-operator
        name: group-sync
      sourceObjectRefs:
        - apiVersion: k8s.keycloak.org/v2alpha1
          kind: Keycloak
          namespace: keycloak
          name: keycloak
      patchTemplate: |
        spec:
          providers:
            - name: keycloak
              keycloak:
                loginRealm: master
                realm: vagabond-studios
                url: https://{{ (index . 1).spec.hostname.hostname }}
                prune: false
                scope: sub
                credentialsSecret:
                  kind: Secret
                  name: keycloak-credentials
                  namespace: group-sync-operator
      patchType: application/merge-patch+json
