default:
  app:
    enabled: true
    enableAutoSync: true
    autoSyncPrune: true
    project: cluster-config
    destination:
      namespace: openshift-gitops
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/tim-stasse/aws-sandbox-sno-gitops
      targetRevision: HEAD

projects:
  cluster-config:
    description: Project for overall cluster configuration
    namespace: openshift-gitops
    sourceRepos:
      - https://github.com/tim-stasse/aws-sandbox-sno-gitops
      - https://github.com/tim-stasse/gitops-catalog
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'

applications:
  ack-system:
    annotations:
      argocd.argoproj.io/sync-wave: "1"
    destination:
      namespace: ack-system
    source:
      path: ack-system/overlays/default

  patch-operator:
    annotations:
      argocd.argoproj.io/sync-wave: "1"
    destination:
      namespace: patch-operator
    source:
      repoURL: https://github.com/tim-stasse/gitops-catalog
      path: patch-operator/operator/overlays/alpha

  patch-operator-config:
    annotations:
      argocd.argoproj.io/sync-wave: "2"
    destination:
      namespace: patch-operator
    source:
      path: patch-operator-config/overlays/default
    extraFields: |
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: MutatingWebhookConfiguration
          jqPathExpressions:
            - .webhooks[].clientConfig.caBundle

  external-secrets-operator:
    annotations:
      argocd.argoproj.io/sync-wave: "3"
    destination:
      namespace: openshift-operators
    source:
      repoURL: https://github.com/tim-stasse/gitops-catalog
      path: external-secrets-operator/operator/overlays/stable

  external-secrets-instance:
    annotations:
      argocd.argoproj.io/sync-wave: "4"
    destination:
      namespace: external-secrets
    source:
      repoURL: https://github.com/tim-stasse/gitops-catalog
      path: external-secrets-operator/instance/overlays/default

  external-secrets-config:
    annotations:
      argocd.argoproj.io/sync-wave: "4"
    destination:
      namespace: external-secrets
    source:
      path: external-secrets-config/overlays/default

  openshift-cert-manager-operator:
    annotations:
      argocd.argoproj.io/sync-wave: "5"
    destination:
      namespace: cert-manager-operator
    source:
      repoURL: https://github.com/tim-stasse/gitops-catalog
      path: openshift-cert-manager-operator/operator/overlays/stable-v1

  cert-manager-config:
    annotations:
      argocd.argoproj.io/sync-wave: "6"
    destination:
      namespace: cert-manager
    source:
      path: cert-manager-config/overlays/default
    extraFields: |
      ignoreDifferences:
        - group: cert-manager.io
          kind: ClusterIssuer
          jqPathExpressions:
            - .spec.acme.solvers[].dns01.route53 | (.region, .hostedZoneID)

  openshift-config:
    annotations:
      argocd.argoproj.io/sync-wave: "6"
    destination:
      namespace: openshift-config
    source:
      path: openshift-config/overlays/default
    extraFields: |
      ignoreDifferences:
        - group: cert-manager.io
          kind: Certificate
          jqPathExpressions:
            - .spec | (.commonName, .dnsNames[])
        - group: config.openshift.io
          kind: APIServer
          jqPathExpressions:
            - .spec.servingCerts.namedCertificates[]
