default:
  app:
    enabled: true
    enableAutoSync: true
    autoSyncPrune: true
    project: cluster-config
    destination:
      namespace: openshift-gitops
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/tim-stasse/aws-sandbox-sno-gitops
      targetRevision: HEAD

projects:
  cluster-config:
    description: Project for overall cluster configuration
    namespace: openshift-gitops
    sourceRepos:
      - https://github.com/tim-stasse/aws-sandbox-sno-gitops
      - https://github.com/tim-stasse/gitops-catalog
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'

applications:
  ack-system:
    annotations:
      argocd.argoproj.io/sync-wave: "1"
    destination:
      namespace: ack-system
    source:
      path: ack-system/overlays/default

  patch-operator:
    annotations:
      argocd.argoproj.io/sync-wave: "1"
    destination:
      namespace: patch-operator
    source:
      repoURL: https://github.com/tim-stasse/gitops-catalog
      path: patch-operator/operator/overlays/alpha

  patch-operator-config:
    annotations:
      argocd.argoproj.io/sync-wave: "2"
    destination:
      namespace: patch-operator
    source:
      path: patch-operator-config/overlays/default
    extraFields: |
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: MutatingWebhookConfiguration
          jqPathExpressions:
            - .webhooks[].clientConfig.caBundle

  external-secrets-operator:
    annotations:
      argocd.argoproj.io/sync-wave: "3"
    destination:
      namespace: openshift-operators
    source:
      repoURL: https://github.com/tim-stasse/gitops-catalog
      path: external-secrets-operator/operator/overlays/stable

  external-secrets-instance:
    annotations:
      argocd.argoproj.io/sync-wave: "4"
    destination:
      namespace: external-secrets
    source:
      repoURL: https://github.com/tim-stasse/gitops-catalog
      path: external-secrets-operator/instance/overlays/default

  external-secrets-config:
    annotations:
      argocd.argoproj.io/sync-wave: "4"
    destination:
      namespace: external-secrets
    source:
      path: external-secrets-config/overlays/default

  openshift-cert-manager-operator:
    annotations:
      argocd.argoproj.io/sync-wave: "5"
    destination:
      namespace: cert-manager-operator
    source:
      repoURL: https://github.com/tim-stasse/gitops-catalog
      path: openshift-cert-manager-operator/operator/overlays/stable-v1

  crossplane-system:
    annotations:
      argocd.argoproj.io/sync-wave: "5"
    destination:
      namespace: crossplane-system
    source:
      repoURL: https://github.com/tim-stasse/gitops-catalog
      path: crossplane-system/overlays/stable

  redhat-keycloak-operator:
    annotations:
      argocd.argoproj.io/sync-wave: "5"
    destination:
      namespace: keycloak
    source:
      repoURL: https://github.com/tim-stasse/gitops-catalog
      path: redhat-keycloak/operator/overlays/stable-v24

  group-sync-operator:
    annotations:
      argocd.argoproj.io/sync-wave: "5"
    destination:
      namespace: group-sync-operator
    source:
      repoURL: https://github.com/tim-stasse/gitops-catalog
      path: group-sync-operator/overlays/alpha

  cert-manager-config:
    annotations:
      argocd.argoproj.io/sync-wave: "6"
    destination:
      namespace: cert-manager
    source:
      path: cert-manager-config/overlays/default
    extraFields: |
      ignoreDifferences:
        - group: cert-manager.io
          kind: ClusterIssuer
          jqPathExpressions:
            - .spec.acme.solvers[].dns01.route53 | (.region, .hostedZoneID)

  crossplane-providers:
    annotations:
      argocd.argoproj.io/sync-wave: "6"
    destination:
      namespace: crossplane-system
    source:
      path: crossplane-providers/overlays/default

  redhat-keycloak-instance:
    annotations:
      argocd.argoproj.io/sync-wave: "6"
    destination:
      namespace: keycloak
    source:
      path: redhat-keycloak-instance/overlays/default
    extraFields: |
      ignoreDifferences:
        - group: cert-manager.io
          kind: Certificate
          jqPathExpressions:
            - .spec | (.commonName, .dnsNames[])
        - group: k8s.keycloak.org
          kind: Keycloak
          jqPathExpressions:
            - .spec.hostname

  crossplane-provider-config:
    annotations:
      argocd.argoproj.io/sync-wave: "7"
    destination:
      namespace: crossplane-system
    source:
      path: crossplane-provider-config/overlays/default
    extraFields: |
      ignoreDifferences:
        - kind: Secret
          name: keycloak-credentials
          jqPathExpressions:
            - .data

  redhat-keycloak-config:
    annotations:
      argocd.argoproj.io/sync-wave: "8"
    destination:
      namespace: keycloak
    source:
      path: redhat-keycloak-config/overlays/default
    extraFields: |
      ignoreDifferences:
        - group: console.openshift.io
          kind: ConsoleLink
          name: keycloak-link
          jqPathExpressions:
            - .spec.href
        - group: openidclient.keycloak.crossplane.io
          kind: Client
          jqPathExpressions:
            - .spec.forProvider.rootUrl

  group-sync-config:
    annotations:
      argocd.argoproj.io/sync-wave: "8"
    destination:
      namespace: group-sync-operator
    source:
      path: group-sync-config/overlays/default
    extraFields: |
      ignoreDifferences:
        - group: redhatcop.redhat.io
          kind: GroupSync
          jqPathExpressions:
            - .spec.providers

  openshift-servicemesh-operator:
    annotations:
      argocd.argoproj.io/sync-wave: "8"
    destination:
      namespace: openshift-operators
    source:
      repoURL: https://github.com/tim-stasse/gitops-catalog
      path: openshift-servicemesh/operator/overlays/tech-preview

  gateway-api-crd:
    annotations:
      argocd.argoproj.io/sync-wave: "8"
    destination:
      namespace: openshift-gitops
    source:
      path: gateway-api/crd/overlays/default

  openshift-servicemesh-cni-instance:
    annotations:
      argocd.argoproj.io/sync-wave: "9"
    destination:
      namespace: istio-cni
    source:
      repoURL: https://github.com/tim-stasse/gitops-catalog
      path: openshift-servicemesh/v3-cni-instance/overlays/default

  openshift-servicemesh-instance:
    annotations:
      argocd.argoproj.io/sync-wave: "9"
    destination:
      namespace: istio-system
    source:
      repoURL: https://github.com/tim-stasse/gitops-catalog
      path: openshift-servicemesh/v3-instance/overlays/default

  rhcl-operator:
    annotations:
      argocd.argoproj.io/sync-wave: "10"
    destination:
      namespace: openshift-operators
    source:
      repoURL: https://github.com/tim-stasse/gitops-catalog
      path: redhat-connectivity-link/operator/overlays/stable

  rhcl-config:
    annotations:
      argocd.argoproj.io/sync-wave: "11"
    destination:
      namespace: api-gateway
    source:
      path: rhcl-config/overlays/default
    extraFields: |
      ignoreDifferences:
        - group: gateway.networking.k8s.io
          kind: Gateway
          jqPathExpressions:
            - .spec.listeners

  openshift-config:
    annotations:
      argocd.argoproj.io/sync-wave: "11"
    destination:
      namespace: openshift-config
    source:
      path: openshift-config/overlays/default
    extraFields: |
      ignoreDifferences:
        - group: cert-manager.io
          kind: Certificate
          jqPathExpressions:
            - .spec | (.commonName, .dnsNames[])
        - group: config.openshift.io
          kind: APIServer
          jqPathExpressions:
            - .spec.servingCerts.namedCertificates[]
        - group: config.openshift.io
          kind: OAuth
          jqPathExpressions:
            - .spec.identityProviders
