apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lvms-vgsno
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: topolvm.io
