apiVersion: kuadrant.io/v1
kind: TLSPolicy
metadata:
  name: external-tls
  namespace: api-gateway
spec:
  targetRef:
    name: external
    group: gateway.networking.k8s.io
    kind: Gateway
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
