kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-gateway-patches-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: api-gateway
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
