apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: ocp-oauth-client
spec:
  forProvider:
    clientId: ocp-oauth
    name: ${client_ocp-oauth}
    realmId: vagabond-studios
    rootUrl: https://oauth-openshift.apps.${CLUSTER_BASE_DOMAIN}/oauth2callback
    validRedirectUris:
      - /oidckeycloak
    accessType: CONFIDENTIAL
    clientAuthenticatorType: client-secret
    clientSecretSecretRef:
      namespace: keycloak
      name: ocp-oauth
      key: client-secret
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    consentRequired: false
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientDefaultScopes
metadata:
  name: ocp-oauth-client-default-scopes
spec:
  forProvider:
    clientId: ocp-client
    realmId: vagabond-studios
    defaultScopes:
      - profile
      - email
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: client-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ocp-oauth-client-secret
spec:
  target:
    name: ocp-oauth
    template:
      engineVersion: v2
      data:
        client-secret: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: client-secret
