apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: ocp-oauth-client
spec:
  forProvider:
    clientId: ocp-oauth
    name: ${client_ocp-oauth}
    realmId: vagabond-studios
    rootUrl: https://oauth-openshift.apps.${CLUSTER_BASE_DOMAIN}/oauth2callback
    validRedirectUris:
      - /oidckeycloak
    accessType: CONFIDENTIAL
    clientAuthenticatorType: client-secret
    clientSecretSecretRef:
      name: ocp-oauth
      key: client-secret
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    consentRequired: false
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientDefaultScopes
metadata:
  name: ocp-oauth-client-default-scopes
spec:
  forProvider:
    clientId: ocp-client
    realmId: vagabond-studios
    defaultScopes:
      - profile
      - email
