apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tim-stasse-initial-password
spec:
  target:
    name: tim-stasse-initial-password
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password-generator
