apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: keycloak-config-patches
spec:
  serviceAccountRef:
    name: default
  patches:
    console-link:
      targetObjectRef:
        apiVersion: console.openshift.io/v1
        kind: ConsoleLink
        name: keycloak-link
      sourceObjectRefs:
        - apiVersion: k8s.keycloak.org/v2alpha1
          kind: Keycloak
          name: keycloak
          namespace: keycloak
      patchTemplate: |
        spec:
          href: https://{{ (index . 1).spec.hostname.hostname }}
      patchType: application/merge-patch+json
    ocp-oauth-client:
      targetObjectRef:
        apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
        kind: Client
        name: ocp-oauth-client
        namespace: keycloak
      sourceObjectRefs:
        - apiVersion: config.openshift.io/v1
          kind: DNS
          name: cluster
      patchTemplate: |
        spec:
          forProvider:
            rootUrl: https://oauth-openshift.apps.{{ (index . 1).spec.baseDomain }}/oauth2callback
      patchType: application/merge-patch+json
