apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: tim-stasse
spec:
  forProvider:
    realmId: vagabond-studios
    username: tim.stasse
    firstName: Tim
    lastName: Stasse
    email: tim.stasse@gmail.com
    emailVerified: true
    initialPassword:
      - temporary: true
        valueSecretRef:
          name: tim-stasse-initial-password
          namespace: keycloak
          key: password
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: Groups
metadata:
  name: tim-stasse-groups
spec:
  forProvider:
    realmId: vagabond-studios
    userIdRef:
      name: tim-stasse
    groupIdsRefs:
      - name: admin-group
