apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/tim-stasse/gitops-catalog/patch-operator/operator/overlays/alpha?ref=main

components:
  - github.com/tim-stasse/aws-sandbox-sno-gitops/patch-operator/operator/components/resources?ref=main
