apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-api-certs
  namespace: openshift-config
spec:
  secretName: cluster-api-certs-tls
  duration: 168h0m0s
  renewBefore: 1h0m0s
  commonName: << common_name >>
  usages:
    - server auth
  dnsNames:
    - << dns_name >>
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
    group: cert-manager.io
