apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-ingress-certs
  namespace: openshift-ingress
  annotations:
    redhat-cop.redhat.io/patch: |
      spec:
        commonName: "*.apps.{{ (lookup "v1" "DNS" "openshift-config" "cluster").spec.baseDomain }}"
        dnsNames:
          - "*.apps.{{ (lookup "v1" "DNS" "openshift-config" "cluster").spec.baseDomain }}"
spec:
  secretName: cluster-ingress-certs-tls
  duration: 168h0m0s
  renewBefore: 1h0m0s
  commonName: << common_name >>
  usages:
    - server auth
  dnsNames:
    - << dns_name >>
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
