apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
spec:
  plugins:
    - monitoring-plugin
    - networking-console-plugin
    - gitops-plugin
    - kuadrant-console-plugin
