apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous

resources:
  - oidc-client-secret.yaml
  - cluster-ingress-certificate.yaml
  - ingress-controller.yaml
  - cluster-api-certificate.yaml
  - api-server.yaml
  - oauth.yaml
  - console.yaml
  - patches-rbac.yaml
  - patches.yaml
