
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous

resources:
  - cluster-ingress-certificate.yaml
  - ingress-controller.yaml
  - cluster-api-certificate.yaml
  - api-server.yaml
