apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            namespace: external-secrets
            name: aws-secretsmanager-creds
            key: aws_access_key_id
          secretAccessKeySecretRef:
            namespace: external-secrets
            name: aws-secretsmanager-creds
            key: aws_secret_access_key
