apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: external-secrets-aws-secretsmanager
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: aws-secretsmanager-creds
    namespace: external-secrets
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
      - effect: Allow
        action:
          - secretsmanager:GetResourcePolicy
          - secretsmanager:GetSecretValue
          - secretsmanager:DescribeSecret
          - secretsmanager:ListSecretVersionIds
        resource: "*"
