apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: keycloak-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: sno/cluster-config/keycloak-db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: sno/cluster-config/keycloak-db-credentials
        property: password
