apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-certs
spec:
  secretName: tls-certs
  isCA: false
  commonName: << common_name >>
  dnsNames:
    - << dns_name >>
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
