apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak-db-credentials.yaml
  - tls-certs.yaml
  - patches-rbac.yaml
  - patches.yaml
  - postgres.yaml
  - keycloak.yaml
