apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: keycloak-patches
spec:
  serviceAccountRef:
    name: default
  patches:
    keycloak-certs:
      targetObjectRef:
        apiVersion: cert-manager.io/v1
        kind: Certificate
        name: keycloak-certs
      sourceObjectRefs:
        - apiVersion: config.openshift.io/v1
          kind: DNS
          name: cluster
      patchTemplate: |
        spec:
          commonName: 'keycloak-ingress-keycloak.apps.{{ (index . 1).spec.baseDomain }}'
          dnsNames:
            - 'keycloak-ingress-keycloak.apps.{{ (index . 1).spec.baseDomain }}'
      patchType: application/merge-patch+json
