apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: keycloak-patches
spec:
  serviceAccountRef:
    name: default
  patches:
    keycloak-hostname:
      targetObjectRef:
        apiVersion: k8s.keycloak.org/v2alpha1
        kind: Keycloak
        name: keycloak
      sourceObjectRefs:
        - apiVersion: config.openshift.io/v1
          kind: DNS
          name: cluster
      patchTemplate: |
        spec:
          hostname:
            hostname: keycloak.apps.{{ (index . 1).spec.baseDomain }}
      patchType: application/merge-patch+json
    tls-certs:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        name: tls-certs
      sourceObjectRefs:
        - apiVersion: v1
          kind: Secret
          name: cluster-ingress-certs-tls
          namespace: openshift-ingress
      patchTemplate: |
        data:
          cert: {{ (index (index . 1).data "tls.crt") }}
          key: {{ (index (index . 1).data "tls.key") }}
      patchType: application/merge-patch+json
